/**
 * Generated by "@vuepress/internal-root-mixins"
 */
import m0 from "D:\\dev\\nvm\\v12.13.1\\node_modules\\vuepress\\node_modules\\@vuepress\\core\\lib\\client\\root-mixins\\updateMeta.js"
import m1 from "D:\\dev\\nvm\\v12.13.1\\node_modules\\vuepress\\node_modules\\@vuepress\\plugin-active-header-links\\clientRootMixin.js"
import m2 from "D:\\dev\\nvm\\v12.13.1\\node_modules\\vuepress\\node_modules\\@vuepress\\plugin-nprogress\\clientRootMixin.js"

export default [
  m0,
  m1,
  m2
]