/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "小豪云上解忧铺",
  "description": "解决前端疑难杂症",
  "base": "/vuepress/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "actionText": "开始 →",
        "actionLink": "/container/"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-581f7bcb",
      "path": "/"
    },
    {
      "frontmatter": {
        "Navbar": false
      },
      "regularPath": "/container/",
      "relativePath": "container/README.md",
      "key": "v-065fead8",
      "path": "/container/"
    }
  ],
  "themeConfig": {
    "docsBranch": "gh-pages",
    "editLinks": true,
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "目录",
        "link": "/container/"
      }
    ],
    "sidebar": [
      {
        "title": "JavaScript",
        "collapsable": false,
        "children": [
          {
            "title": "变量"
          },
          {
            "title": "数组"
          }
        ]
      },
      {
        "title": "Vue2",
        "children": []
      },
      {
        "title": "PHP",
        "children": []
      }
    ]
  }
}