/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "actionText": "开始 →",
        "actionLink": "/container/",
        "features": [
          {
            "title": "Simplicity First",
            "details": "Minimal setup with markdown-centered project structure helps you focus on writing."
          },
          {
            "title": "Vue-Powered",
            "details": "Enjoy the dev experience of Vue + webpack, use Vue components in markdown, and develop custom themes with Vue."
          },
          {
            "title": "Performant",
            "details": "VuePress generates pre-rendered static HTML for each page, and runs as an SPA once a page is loaded."
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-581f7bcb",
      "path": "/"
    },
    {
      "title": "666",
      "frontmatter": {},
      "regularPath": "/container/",
      "relativePath": "container/README.md",
      "key": "v-065fead8",
      "path": "/container/",
      "headers": [
        {
          "level": 2,
          "title": "666",
          "slug": "_666"
        }
      ]
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "Guide",
        "link": "/container/"
      }
    ]
  }
}